### ISSUE TITLE
Not working in admin with autocomplete_fields

### ISSUE THREAD

**Issue by eriktelepovsky** [agusmakmun/django-markdown-editor#100] opened 2019-11-26 15:07 UTC
Hi. I noticed Martor editor works fine until there is **autocomplete_fields** defined in the admin:

```Python
@admin.register(Article)
class ArticleAdmin(admin.ModelAdmin):
    search_fields = ('title', 'category__title', 'content')
    date_hierarchy = 'created'
    list_display = ('title', 'category', 'created', 'modified')
    list_filter = ('category',)
    list_select_related = ['category']
    # autocomplete_fields = ['category']  # not working with martor
```

Console error:

```JavaScript
Uncaught TypeError: $(...).dropdown is not a function
    at HTMLDocument.<anonymous> (martor.js:848)
    at mightThrow (jquery.js:3535)
    at process (jquery.js:3603)
```

Config:

```Python
MARTOR_ENABLE_CONFIGS = {
    'spellcheck': 'false',
    'imgur': 'true',     # to enable/disable imgur/custom uploader.
    'mention': 'false',  # to enable/disable mention
    'jquery': 'true',    # to include/revoke jquery (require for admin default django)
}
```

Tested on versions:
```
Django==2.2.6
Markdown==3.1.1
martor==1.4.4
```

**Comment by virusdefender** [comment] 2020-03-18 09:42
+1

**Comment by onurmatik** [comment] 2020-04-21 18:23
It maybe a namespace conflict with select2. Django uses select2 for admin autocomplete fields.

**Comment by eriktelepovsky** [comment] 2020-06-08 13:46
Any fix for this yet?

**Comment by some1ataplace** [comment] 2023-04-05 01:41
Might be related to the dropdown function in the jQuery library. Load jquery before the martor editor or Martor's JavaScript should be loaded before the jQuery import in your HTML template.

```
{% extends "admin/base.html" %}

{% block extrahead %}
    {{ block.super }}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    {{ form.media }}
{% endblock %}

{% block content %}
    {{ block.super }}
    {{ form.as_p }}
{% endblock %}
```


```
    {% load static %}
    <script type="text/javascript" src="{% static 'path/to/martor.js' %}"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
```


```
MARTOR_ENABLE_CONFIGS = {
'auto_urlize': 'false'
}
```

Disabling the autocomplete_fields option for the Article model in the Django admin, as it seems to be the root cause of the issue. You can do this by commenting out the line autocomplete_fields = ['category'] in the ArticleAdmin class:

```
@admin.register(Article)
class ArticleAdmin(admin.ModelAdmin):
    search_fields = ('title', 'category__title', 'content')
    date_hierarchy = 'created'
    list_display = ('title', 'category', 'created', 'modified')
    list_filter = ('category',)
    list_select_related = ['category']
    # autocomplete_fields = ['category']  
```

**Comment by agusmakmun** [comment] 2024-03-30 08:59
Hello @eriktelepovsky, seems this issue has been resolved in the latest version.

![Screenshot 2024-03-30 at 15 58 34](https://github.com/agusmakmun/django-markdown-editor/assets/7134451/67d8c851-d72b-4b26-82d7-1e002af5cca9)

Try to upgrade your martor version:
```
pip install martor --upgrade
```

Let me know if this issue still persists.

**Closed by agusmakmun** 2024-03-30 08:59 UTC
